# Generated by hand for PhoneVerificationCode model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_telegram", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneVerificationCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phone", models.CharField(db_index=True, max_length=32)),
                ("code", models.CharField(max_length=6)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
